Repository stolostron/ansible-collection.core, pull requests merged in 2022-06, with the labels that each got.

#137 starting to reference rhacm docs
  README.md
Labels: approved, lgtm

#139 Rename stolostron core
  .github/workflows/ansible-test-integration.yml
  .github/workflows/ansible-test.yml
  .github/workflows/docs-pr.yml
  .github/workflows/galaxy-publish-check.yml
  CHANGELOG.rst
  README.md
  changelogs/archive_fragments/0.0.1-alpha.yml
  changelogs/archive_fragments/0.0.1.yml
  changelogs/changelog.yaml
  changelogs/config.yaml
  docs-build/README.md
  docs-build/build.sh
  docs/cluster_management_addon_module.rst
  docs/cluster_proxy_module.rst
  docs/index.rst
  docs/managed_serviceaccount_module.rst
  docs/managed_serviceaccount_rbac_module.rst
  docs/managedcluster_addon_module.rst
  docs/ocm_managedcluster_inventory.rst
  galaxy.yml
  plugins/inventory/ocm_managedcluster.py
  plugins/module_utils/managedcluster_addons/cluster_proxy.py
  plugins/module_utils/managedcluster_addons/managed_serviceaccount.py
  plugins/module_utils/managedcluster_addons/search_collector.py
  plugins/modules/cluster_management_addon.py
  plugins/modules/cluster_proxy.py
  plugins/modules/managed_serviceaccount.py
  plugins/modules/managed_serviceaccount_rbac.py
  plugins/modules/managedcluster_addon.py
  tests/README.md
  tests/integration/targets/inventory_ocm_managedcluster/template/inventory_ocm.yml.j2
  tests/integration/targets/multicluster_management/tasks/main.yml
  tests/unit/plugins/module_utils/test_installer_utils.py
  tests/unit/plugins/modules/test_managed_serviceaccount_rbac.py
Labels: approved

#144 fixing namespace and collection name in galaxy pub action
  .github/workflows/galaxy-publish.yml
Labels: lgtm

#145 bumping version to 0.0.1-beta and fixing links to gh repo
  README.md
  docs/cluster_management_addon_module.rst
  docs/cluster_proxy_module.rst
  docs/index.rst
  docs/managed_serviceaccount_module.rst
  docs/managed_serviceaccount_rbac_module.rst
  docs/managedcluster_addon_module.rst
  docs/ocm_managedcluster_inventory.rst
  galaxy.yml
Labels: approved, lgtm

#153 adding reference to demo repo
  README.md
Labels: lgtm

#154 shorten cluster name in CI
  .github/workflows/ansible-test-integration.yml
Labels: approved, lgtm
